version: "3.3"

volumes:
  postgres: ~

networks:
  webapp:

services:
  nginx:
    container_name: ${APP_NAME}-nginx
    image: nginx:alpine
    restart: on-failure
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ${PWD}:/app
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/symfony:/etc/nginx/symfony
    links:
      - php
    depends_on:
      - php
      - postgres
    networks:
      - webapp

  postgres:
    container_name: ${APP_NAME}-postgres
    ports:
      - "127.0.0.1:5431:5432"
    image: postgres:alpine
    restart: on-failure
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
    networks:
      - webapp

  php:
    container_name: ${APP_NAME}-php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./:/app
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - postgres
    networks:
      - webapp